language: node_js
node_js:
- 'node'
cache:
  yarn: true
script: yarn test && yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: "./dist/out"
  on:
    branch: next
env:
  global:
  - secure: oHpYPljDQ2IKLFlydJjdm9CPR8yMCxVtqHIwH0U2FyLnTbboa95hNY/6pDEvPfiu9pq3Fg4ZkmbPLfr2/5WbST1no22+1PeGj/avc21HdSR4TMERQ6oJ/7H2Uq+St3Qp1psxXPvcJQ+aXb9rUPkxEeDf2r5Be20ojZUnr/g411jFimHV2k+vqvlNQn4XrYSchszgvA6D9EJ8/cAzA/rH5wp3raynOB08nGE8HxoyTyorX2AyD3mdRQ+H+ax3taSn4R2Ol5xQnN5kPpiRIUphKc4NxXwbfj+/6Ul5q3+aZQqw3OL6q0Fw/ApJVuUVQe88KQ6Y9dtjshHBBs7Ky0Q/wz4ighPkaIqBOOyVHHJlsFQAvt7bGU1d4C0Xz46I41IJ0Uadoyi7r4fc0acgVpPQrc9tT3i7R3cmvSWPSiP06ccXl1BI0AHXOWsZk2lA5FlUr2yvGeVcdQ3N6cT6OEx79AQWBvcbHIPZ9F+pVVHYhfgyN6hbYXdsLX9+AoBZZ7CiDd4XLNoOrKE7e0BalChMBQVURdUjt7FGT4E6lvqdfTRHZpSMgPmjMh6Z2f2XcvyY0xnf04fUdxXyhkUVXs7oRos8fzmqmNsNiMYMgxcwsmVGIWqaE/s7d7OAh8cg+88xfsLO1ZRRyi5D/Jc9pglxyaFKEQ1nkQIbq97vHaScYmY=
