language: node_js
node_js:
  - '8'
  - '6'
cache:
  yarn: true
script: yarn test && yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  'on':
    branch: next
  local_dir: ./dist/out
env:
  global:
    - secure: >-
        CrtFIIXbRswBRgOZ/Q/nONsky4ccOJVyFSrg79WlfVyaIvk6g4GbxDXhd3u3Uqd7d80rTFk5hf7FOjescRKHmVV/keuSs3l72SbSpltd4MaaUHW1BIctr6ENPwAcf2LTq+AkBycvHvBcNoGVSp/tqvi91mAqYjCwgCxhQvs8Yt7b7yc2w0ijXS4T5pSpzVfP6zAzsYG/eMxL+Liic2xPsJj3MNkg0afvB63liaNEdd7q/Co7ZDgupm9PTBFQAbN168SDyR02z//6Shgxp4mW3OVJnEstWRZ6Nkwu598Toa/P3U0tRDv0nJPsF+YvCH5rhF8P1dyp+eWu0y1G/ZmW8uCmS3WEUWVRI2ZMVnza5sks4bbj96LJyuEySKK4aSd3HXsTFmQ/tPFlUKaYpaP0tVbbvq7BjWAGko0ks27XG8SmXWgxS9BljVwg1m4kGC6idI5PpXiMSRDe+CcQkHfjA+8C6Ea8HWtZIBtqXzsi0JiPqs/m3w34B/Nvwt3AmhZcBmnbFiTqnEGh3EyCN9RiwqtrjaKb+OSui5oLXunPQFHcadQiOuqsc+Bqb8s+GBcl6V0JH6lflQt2yeCpRyAFC8CFtZJ3UwnHvlT7HiLzjQhHZMgmm63qJGIgnp5QwolAT3jWhkS/190CjFGPoWnudmSLg2MJblp8MJaVu8IwHWc=
